name: Generate Sitewide SEO Report

on:
  schedule:
    - cron: '0 4 * * 1' # Every Monday at 4:00 AM UTC
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  sitewide-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build --no-cache -t seo-reporter .

      - name: Run sitewide report in container
        run: |
          docker run --rm -v ${{ github.workspace }}/project:/app seo-reporter python3 scripts/GenerateSEOReports.py sitewide_report

      - name: Commit and push updated reports
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add project/templates/lighthouse_reports/
          git commit -m "📊 Weekly sitewide SEO report update [CI]" || echo "No changes to commit"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
